name: DebugBuild
on:
  push:
     branches:
      - master

env:
  # ソリューションのフルパスを指定
  SOLUTION_FILE_PATH: D:\a\TopDown-Shooting\TopDown-Shooting\Engine-Develop\project\Engine.sln
  # Visual Studio の構成(Debug / Release)
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # サブモジュール取得
          
      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Check Solution FIle
        run: ls -R Engine-Develop/project
        
      - name: Add MSBuild to Path
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build
        working-directory: Engine-Develop/project
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
